# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 深入理解java虚拟机 读书笔记
baseurl: "/JVMDocs" # the subpath of your site, e.g. /blog
url: "http://onefengma.com/JVMDocs/" # the base hostname & protocol for your site
github: "https://github.com/chufengma/JVMDocs" # github home page for saogege
#blog link settings
permalink: date
# Build settings
markdown: kramdown
